# Generated by Django 5.0.2 on 2025-06-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backend_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_logo', models.ImageField(upload_to='photos/')),
                ('skill_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Frontend_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_logo', models.ImageField(upload_to='photos/')),
                ('skill_level', models.CharField(max_length=50)),
            ],
        ),
    ]
