# Generated by Django 5.0.7 on 2025-06-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_backend_skill_frontend_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='photos/')),
                ('project_name', models.CharField(max_length=50)),
            ],
        ),
    ]
